# tasks file for this role, can include smaller files if warranted

- name: Update cache
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - os_update

- name: Upgrade all packages
  become: true
  apt:
    upgrade: dist
  tags:
    - os_update

- include_tasks: reboot.yml
  tags:
    - os_update
    - reboot
